apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-docker-repo/backend:latest
        ports:
        - containerPort: 3001
