version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ../backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: your_user
      DB_PASS: your_password
      DB_NAME: your_db
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  pgdata:
