apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: project-management
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
